name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check

  docs_and_spell_check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: 'Check spelling'
        uses: crate-ci/typos@master
      - run: cargo doc --no-deps

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: 'Clippy (moq)'
        run: cargo clippy --all-features --package moq -- -D warnings
      - name: 'Clippy (moq_derive)'
        run: cargo clippy --all-features --package moq_derive -- -D warnings
      - name: 'Clippy (moq_lambda)'
        run: cargo clippy --all-features --package moq_lambda -- -D warnings

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest

      - name: 'Test (moq)'
        run: cargo nextest run --all-features --no-tests=pass --package moq
      - name: 'Test (moq_derive)'
        run: cargo nextest run --all-features --no-tests=pass --package moq_derive
      - name: 'Test (moq_lambda)'
        run: cargo nextest run --all-features --no-tests=pass --package moq_lambda
      - name: 'Test (moq_test_suite)'
        run: cargo nextest run --all-features --no-tests=pass --package moq_test_suite